### PR TITLE
impl'd follow logs (#215)

### LINKED ISSUE #215: As a user I want to be able to follow the logs
related to #214 

When asked why he liked the jetbrains kubernetes plugin a guy responded with the following:
> FYI For people like me that can't live outside their IDE: the Jetbrains Kubernetes plugin is quite good for reading logs and it allows to easily modify resources already in the cluster. I tried it with Intellij IDEA and it works quite well (I guess it's available with Goland too)

### PR DESCRIPTION
**Pull request by adietish**
fixes #215

### CODE REVIEW

**Comment by adietish** [comment]
@olkornii can you please tell me what is failing in the ITs?

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: things are ready to be tested (unit tests are missing though).

**Comment by adietish** [comment]
filed #439 and #440 to enhance what "follow logs" offers in this PR

**Comment by jeffmaury** [comment]
Works ok with the following case: I started follow log just after I created the pod and the container was not yet available because image had to be pulled. It worked ok as I got a message that the container was not yet available but after the pod has been started I did not receive the messages that Apache generates when it starts.

This is the pod definition I used:
```

apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
    - name: apache
      image: httpd:2.4.54
      ports:
        - containerPort: 80
```

**Review by lstocchi — COMMENTED** [review]
Same as Jeff +
i would add an icon to the toolwindow Tab (in line with all other IJ tabs) 
image
For the rest it worked fine

**Comment by adietish** [comment]
>i would add an icon to the toolwindow Tab (in line with all other IJ tabs) image 

added an icon
grafik

**Comment by adietish** [comment]
discussed with @jeffmaury that we should not offer logging for resources that do not produce their own logs but present the ones that are produced their pods because results are puzzling to the user: assume that you have a deployment with 2 pods. Now terminate the pod that is producing the log for the deployment. What you then get is a logging stream that simply stops even though there's a 2nd one present.

**Comment by adietish** [comment]
@jeffmaury if waiting until the pod gets ready I get the exact same output with kubectl and "follow logs" in the plugin:

* kubectl:
```
❯ kubectl logs apache
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.15. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.15. Set the 'ServerName' directive globally to suppress this message
[Wed Jul 06 16:08:22.150719 2022] [mpm_event:notice] [pid 1:tid 140290444995904] AH00489: Apache/2.4.54 (Unix) configured -- resuming normal operations
[Wed Jul 06 16:08:22.150817 2022] [core:notice] [pid 1:tid 140290444995904] AH00094: Command line: 'httpd -D FOREGROUND'
```
* intellij-kubernetes:
```
tpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.15. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.15. Set the 'ServerName' directive globally to suppress this message
[Wed Jul 06 16:06:48.572899 2022] [mpm_event:notice] [pid 1:tid 140540261399872] AH00489: Apache/2.4.54 (Unix) configured -- resuming normal operations
[Wed Jul 06 16:06:48.573113 2022] [core:notice] [pid 1:tid 140540261399872] AH00094: Command line: 'httpd -D FOREGROUND'
```
Am i missing something?

What I think is annoying is that you cannot follow the log for a pod that is not ready yet. You get the API error in the console and you have to close it and open a new console via hit "follow logs" once it gets ready. Maybe we should wait for the pod to get ready before we request the logs?

**Comment by jeffmaury** [comment]
Not sure to understand how its implemented but if I use follow log on a pod that is pending I have the error message:

image

But I never saw the normal error message from Apache (when the pod is available) even if I retry Follow logs

**Comment by adietish** [comment]
@lstocchi, @jeffmaury: I snow only support the following logs:
* Build
* Job
* Pod

**Comment by adietish** [comment]
@lstocchi, @jeffmaury I now try to retrieve the log even if waiting for the resource to become ready fails (like kubectl apparently does). Please review.

**Pull request merged**
