### PR TITLE
Allow java consumers to consume (watch-) Supplier<T> (#102)

### LINKED ISSUE #102: Allow 3rd party extenders (ex intellij-tekton)
This plugin should allow other plugins to use and extend the functionality that's provided in here (ex. tree)

### PR DESCRIPTION
**Pull request by adietish**
fixes #102

### CODE REVIEW

**Review by lstocchi — CHANGES_REQUESTED** [review]
Tested and i found an issue (below). The rest LGTM to me (code and how it works). If you prefer i can also open a new issue and approve this PR. 

I have a problem with the pipeline crd that prevents me to see its items in the tree and also switch to a different namespace.

The plugin thinks that the correct api version is alphav1 but i'm actually using v1beta1 on my cluster. I think i have both as it was v1alpha1 at the beginning and then i updated it to v1beta1.

What i see in the tree 
image

If i try to switch to a different namespace 
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.crc.testing:6443/apis/tekton.dev/v1alpha1/namespaces/tekton-pipelines/pipelines. Message: conversion webhook for tekton.dev/v1beta1, Kind=Pipeline failed: conversion failed to version v1alpha1 for type [kind=Pipeline group=tekton.dev version=v1beta1] -  the specified field/section is not available in v1alpha1. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=conversion webhook for tekton.dev/v1beta1, Kind=Pipeline failed: conversion failed to version v1alpha1 for type [kind=Pipeline group=tekton.dev version=v1beta1] -  the specified field/section is not available in v1alpha1, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:589)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:809)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.list(RawCustomResourceOperationsImpl.java:446)
	at org.jboss.tools.intellij.kubernetes.model.resource.kubernetes.custom.NamespacedCustomResourcesProvider.loadAllResources(NamespacedCustomResourcesProvider.kt:33)
	at org.jboss.tools.intellij.kubernetes.model.resource.NamespacedResourcesProvider.getAllResources(NamespacedResourcesProvider.kt:45)
	at org.jboss.tools.intellij.kubernetes.model.resource.AbstractResourcesProvider.invalidate(AbstractResourcesProvider.kt:23)
	at org.jboss.tools.intellij.kubernetes.model.resource.NamespacedResourcesProvider.setNamespace(NamespacedResourcesProvider.kt:36)
	at org.jboss.tools.intellij.kubernetes.model.context.ActiveContext.setCurrentNamespace(ActiveContext.kt:112)
	at org.jboss.tools.intellij.kubernetes.model.context.ActiveContext.setCurrentNamespace(ActiveContext.kt:103)
	at org.jboss.tools.intellij.kubernetes.model.ResourceModel.setCurrentNamespace(ResourceModel.kt:62)
	at org.jboss.tools.intellij.kubernetes.actions.UseNamespaceAction$actionPerformed$1.run(UseNamespaceAction.kt:31)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I tried the same with the master branch. The error when opening the tree also happens there but the difference is that i'm able to switch namespace. Not sure if it can be helpful.

**Comment by adietish** [comment]
@lstocchi thanks for spotting this. Since it also happens in master, I suggest that we address this in a separate issue: #116

**Comment by adietish** [comment]
@jeffmaury LGTM for you?

**Comment by adietish** [comment]
@lstocchi there's another issue here: you're not able to switch the namespace. An error when retrieving resources (here it's the conversion that's failing) should not make it impossible for you to switch namespaces. I filed this to #118

**Comment by adietish** [comment]
@lstocchi as a simple workaround for now, I'll use the `version` property (instead of the array of available versions in `versions` that I would have to pick the appropriate version from. This works for me.

**Comment by adietish** [comment]
@lstocchi if you agree that we should merge this, then please accept the PR. I'll address the issues that you found in 
* #117
* #118

**Review by lstocchi — APPROVED** [review]
Ok for me to merge this as it is

**Pull request merged**
