### PR TITLE
correctly synchronize accessing client when config changes (#640)

### LINKED ISSUE #640: Use current Namespace/Project has a bug with minikube
Configurations:
  Kubernetes v1.26.2 on Docker 24.0.4
  openjdk 17.0.7 2023-04-18
  OS: Fedora 38
  Intellij 2023.1

Steps to reproduce:
1. Start minikube cluster
2. Expand Namespaces
3. Select namespace -> right click -> Use namespace -> tree refreshed (WRONG BEHAVIOR)
4. Repeat few times -> cluster name changes for short time (sometimes freezes)

On the video's 10 second is a bug.
[Screencast from 2023-07-24 12-22-10.webm](https://github.com/redhat-developer/intellij-kubernetes/assets/60704619/0c129321-6c3a-46a9-ae84-877bd7eec67d)

### PR DESCRIPTION
**Pull request by adietish**
possibly fixes #640 (not sure because I cannot replicate the issue)

### CODE REVIEW

**Comment by datho7561** [comment]
This fixes the issue where the context is replaced with <unknown context> in the tree, but the tree view still refreshes

**Comment by datho7561** [comment]
I tried again, but the latest change doesn't prevent the tree view from refreshing

**Comment by adietish** [comment]
@datho7561 thanks for testing. So I'd suggest to merge the PR since it fixes the critical issue where the context would become <unknown context>. I'd then keep the issue open (or create a new one) for the remaining issue where the refresh is still happening.

**Review by datho7561 — APPROVED** [review]
Yes, that sounds like a good idea!

**Pull request merged**
