### PR TITLE
refresh crd's when watch events notify cr's (#328)

### LINKED ISSUE #328: new pipeline does not appear in tree when pushed via editor
related to #292, #325 

**Steps:**
1. EXEC: File > New > pipeline.yml
2. EXEC: paste following into the editor
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: "2021-12-14T15:31:04Z"
  generation: 5
  name: app-sum-test
  namespace: default
  resourceVersion: "34943221"
  uid: 7f7f5534-493c-4c04-b5f7-aa1837c0840e
spec:
  params:
  - name: first
    type: string
  - name: second
    type: string
  tasks:
  - name: sum
    params:
    - name: a
      value: $(params.first)
    - name: b
      value: $(params.second)
    taskRef:
      kind: Task
      name: sum-params
```
3. EXEC: push to cluster

**Result:**
new pipeline `app-sum-test` does not appear in tree

**Expected result:**
new pipeline `app-sum-test` appears in the tree at **[cluster] > Custom Resources > pipelines**

### PR DESCRIPTION
**Pull request by adietish**
depends on #327 which has to be merged first.
fixes #328

### CODE REVIEW

**Comment by adietish** [comment]
it's important that #306 still works after this change. Here are the steps as taken from #306 

**Steps:**
1. ASSERT:  have a deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
  labels:
    app: nginx-rolling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-rolling
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8080
```
1. EXEC: open deployment in editor (double click deployment in resource tree)
1. ASSERT: **1** pod `nginx-rolling-xxxxxxx` is shown as child to the deployment `nginx-rolling`
1. EXEC: change `spec` > `replicas` to **2** & Push
1. ASSERT: deployment `nginx-rolling` is collapsed
1. EXEC: expand `nginx-rolling`

**Comment by jeffmaury** [comment]
I tried with the sample provided in the issue bot an error when pushing.

Here is the stack trace:

```
2021-12-20 10:02:03,786 [1548834]  ERROR - .impl.MessageBusConnectionImpl - updated must not be null                                                                                           
java.lang.IllegalStateException: updated must not be null                                                                                                                                      
        at com.redhat.devtools.intellij.kubernetes.model.resource.kubernetes.custom.NamespacedCustomResourceOperator.get(NamespacedCustomResourceOperator.kt:80)                               
        at com.redhat.devtools.intellij.kubernetes.model.ClusterResource.request(ClusterResource.kt:100)                                                                                       
        at com.redhat.devtools.intellij.kubernetes.model.ClusterResource.get(ClusterResource.kt:87)                                                                                            
        at com.redhat.devtools.intellij.kubernetes.model.ClusterResource.isOutdated(ClusterResource.kt:189)                                                                                    
        at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.showNotifications(ResourceEditor.kt:160)                                                                              
        at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.update(ResourceEditor.kt:147)                                                                                         
        at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.update(ResourceEditor.kt:136)                                                                                         
        at com.redhat.devtools.intellij.kubernetes.editor.EditorFocusListener.handleSelectionGained(EditorFocusListener.kt:42)                                                                 
        at com.redhat.devtools.intellij.kubernetes.editor.EditorFocusListener.selectionChanged(EditorFocusListener.kt:26)                                                                      
        at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)                                                                                                               
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                            
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                          
        at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:513)                                                                                              
        at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:142)                                                                          
        at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:438)                                                                                              
        at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)                                                                                            
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:388)                                                                                                
        at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)                                                                                                 
        at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:241)                                                                                 
        at com.sun.proxy.$Proxy93.selectionChanged(Unknown Source)                                                                                                                             
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$fireSelectionChanged$21(FileEditorManagerImpl.java:1576)                                                          
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$6$1.run(FileEditorManagerImpl.java:1019)                                                                                 
        at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:168)                                                                            
        at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2413)                                                                                                                   
        at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:177)                                                                                                      
        at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:129)                                                                                        
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:159)                                                                                     
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:165)                                                                                     
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:41)                                                                                
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$6.run(FileEditorManagerImpl.java:1016)                                                                                   
        at com.intellij.openapi.util.BusyObject$Impl$Simple.execute(BusyObject.java:108)                                                                                                       
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.notifyPublisher(FileEditorManagerImpl.java:1012)                                                                         
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.fireSelectionChanged(FileEditorManagerImpl.java:1576)                                                                    
        at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$setCurrentWindow$4(EditorsSplitters.java:625)                                                                          
        at com.intellij.openapi.fileEditor.impl.EditorsSplitters.setCurrentWindow(EditorsSplitters.java:634)                                                                                   
        at com.intellij.openapi.fileEditor.impl.EditorWindow.setEditor(EditorWindow.java:546)                                                                                                  
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:882)                                                                         
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$null$7(FileEditorManagerImpl.java:819)                                                                            
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1671)                                                                        
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$8(FileEditorManagerImpl.java:818)                                                                   
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:519)                                                                                       
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:532)                                                                                       
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:817)                                                                            
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:762)                                                                            
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:745)                                                                   
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)                                                                                
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)                                                                                
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)                                                                                
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)                                                                                
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:745)                                                                            
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:676)                                                                    
        at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:142)                                                                                       
        at com.intellij.codeInsight.navigation.NavigationUtil.activatePsiElementIfOpen(NavigationUtil.java:203)                                                                                
        at com.intellij.codeInsight.navigation.NavigationUtil.lambda$openFileWithPsiElement$1(NavigationUtil.java:173)                                                                         
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)                                                                                
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)                                                                                
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)                                                                                
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)                                                                                
        at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:172)                                                                                  
        at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:237)                                                                                
        at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:247)                                                                                
        at com.intellij.ide.projectView.impl.nodes.PsiFileNode.navigate(PsiFileNode.java:115)                                                                                                  
        at com.intellij.util.OpenSourceUtil.navigateToSource(OpenSourceUtil.java:119)                                                                                                          
        at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:74)                                                                                                                   
        at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:58)                                                                                                                   
        at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:51)                                                                                                                   
        at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:19)                                                                                                            
        at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:129)                                                      
        at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:121)                                                           
        at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)                                                                                                            
        at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)                                                                                                                
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)                                                                                               
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)                                                                                               
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)                                                                                               
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)                                                                                               
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)                                                                                                              
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)                                                                                                         
        at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:391)                                                                                                                 
        at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:43)                                                                                                     
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)                                                                                                                   
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)                                                                                                                   
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)                                                                                                              
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)                                                                                                              
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)                                                                                                                  
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)                                                                                                 
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)                                                                                                  
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)                                                                                                      
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)                                                                                                              
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)                                                                                                                    
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)                                                                                                                  
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)                                                                                                             
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)                                                                                                                         
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)                                                                                                                         
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                                                
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)                                                                   
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)                                                                   
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)                                                                                                                         
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)                                                                                                                         
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                                                
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)                                                                   
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)                                                                                                                 
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)                                                                                                         
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)                                                                                                           
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)                                                                                                               
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)                                                                                                       
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)                                                                             
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)                                                                                                                
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)                                                                                      
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)                                                                                         
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)                                                                                      
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)                                                                                                  
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                                                                                  
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)                                                                                                          
2021-12-20 10:02:03,786 [1548834]  ERROR - .impl.MessageBusConnectionImpl - IntelliJ IDEA 2019.3  Build #IC-193.5233.102                                                                       
2021-12-20 10:02:03,786 [1548834]  ERROR - .impl.MessageBusConnectionImpl - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o                                                 
2021-12-20 10:02:03,787 [1548835]  ERROR - .impl.MessageBusConnectionImpl - OS: Windows 10                                                                                                     
2021-12-20 10:02:03,787 [1548835]  ERROR - .impl.MessageBusConnectionImpl - Plugin to blame: Kubernetes by Red Hat version: 0.2.5                                                              
2021-12-20 10:02:03,787 [1548835]  ERROR - .impl.MessageBusConnectionImpl - Last Action: EditorCopy                                                                                            
2021-12-20 10:02:03,787 [1548835]  ERROR - .impl.MessageBusConnectionImpl - Current Command:                                                                                                   
```

**Comment by adietish** [comment]
> I tried with the sample provided in the issue bot an error when pushing.
> 
> Here is the stack trace:
> 
> ```
> 2021-12-20 10:02:03,786 [1548834]  ERROR - .impl.MessageBusConnectionImpl - updated must not be null                                                                                           
> java.lang.IllegalStateException: updated must not be null                                                                                                                                      

This looks exactly like the error that was fixed in #317. Wondering if this PR is properly rebased.

**Comment by adietish** [comment]
@jeffmaury I can't replicate your error, so I'm trying to guess what happened.  Do you have the tekton pipeline crd?

**Comment by jeffmaury** [comment]
> @jeffmaury I can't replicate your error, so I'm trying to guess what happened. Do you have the tekton pipeline crd?

Yes it's running against my Minikube Tekton VM

**Comment by jeffmaury** [comment]
ijkube

using Tekton Pipelines v0.31.0

**Comment by adietish** [comment]
@jeffmaury there's something that's different from my setup. When I do the same, I have a push/create new notification right after the push:
Screen Recording 2021-12-21 at 12 07 09(1)

**Comment by adietish** [comment]
@jeffmaury what's your version of minikube, kuberentes?
There's another thing that odd: the line number in your stack trace points to a line number without code.
> NamespacedCustomResourceOperator.kt:80
https://github.com/redhat-developer/intellij-kubernetes/blob/master/src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/resource/kubernetes/custom/NamespacedCustomResourceOperator.kt#L80
image

**Comment by jeffmaury** [comment]
> @jeffmaury what's your version of minikube, kuberentes?
> 
> There's another thing that odd: the line number in your stack trace points to a line number without code.
> 
> > NamespacedCustomResourceOperator.kt:80
> 
> https://github.com/redhat-developer/intellij-kubernetes/blob/master/src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/resource/kubernetes/custom/NamespacedCustomResourceOperator.kt#L80 image

Minikube: 1.24
Kube: 1.22.3

I was on the wrong PR while testing so LGTM

**Pull request merged**
