### PR TITLE
feat: show decoded value for base64 values in Secrets, ConfigMaps (#663)

### LINKED ISSUE #663: As a user I would like to easily create/edit Secrets in the editor
3rd most upvoted feature in vscode-kubernetes-tools: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/579

The idea is to handle base64 encoding transparently like https://github.com/rajatjindal/kubectl-modify-secret does. Secret is presented decoded and is encoded automatically when pushed to the cluster.

### PR DESCRIPTION
**Pull request by adietish**
fixes #663 

`Secrets` and `ConfigMaps` to test this PR: [secrets-configmaps.zip](https://github.com/redhat-developer/intellij-kubernetes/files/14336192/secrets-configmaps.zip)

### CODE REVIEW

**Comment by adietish** [comment]
Current impl works fine for 1-line secrets:
Screen-Recording-2024-02-15-at-1

I am current working on displaying hints and editing multiline secrets.

**Comment by adietish** [comment]
I now added display & edit for multiline values:
image

**Comment by adietish** [comment]
I decided to have binary data shown as hex-values, not allowing them to be edited. 

image

I could have provided them to be edited in binary form via a `JFormattedTextField` (see https://docs.oracle.com/javase/tutorial/uiswing/components/formattedtextfield.html) but I'm unsure if this would be useful and match real-world use cases. I thus didn't go for it for now.
One could have a f

**Comment by adietish** [comment]
Here are some examples that can be used to test this PR: [secrets-configmaps.zip](https://github.com/redhat-developer/intellij-kubernetes/files/14336192/secrets-configmaps.zip)

**Comment by adietish** [comment]
@sbouchet, @datho7561: please review. I attached a zip with several secrets and configmaps to test this. Thanks :)

**Comment by adietish** [comment]
While waiting for the reivew I'm adding unit-tests.

**Comment by datho7561** [comment]
I connected to OpenShift Sandbox and opened the secrets files for the service accounts, but none of the values are show as inlay hints. I expect this is because all the values are all in double quotes.

**Comment by datho7561** [comment]
When working with a string with newlines in it, if I want to add another newline, I can add the first one, but when I try to add a second one, it closes the text box and applies the new value.

**Comment by adietish** [comment]
> I connected to OpenShift Sandbox and opened the secrets files for the service accounts, but none of the values are show as inlay hints. I expect this is because all the values are all in double quotes.

thanks for finding this, I'll look into it and try to fix it.

**Comment by adietish** [comment]
> When working with a string with newlines in it, if I want to add another newline, I can add the first one, but when I try to add a second one, it closes the text box and applies the new value.

@datho7561: Me thinks that it would be only possible to allow several empty lines when confirming the dialog would be via a dedicated button. Worth it?

**Comment by adietish** [comment]
> > Worth it?
> 
> I think so

Ok, adding a button then. Thanks for pointing this out 🙂

**Comment by sbouchet** [comment]
same comments as @datho7561 , display is correct, edition is ok for single lines values and need chenges for multiline

**Comment by sbouchet** [comment]
latest changes did not changed behavior for multiple lines edit (second hit on ENTER closes the dialog).

it's even worst because now multiple line aren't displayed on local yaml
Capture d’écran du 2024-02-21 14-57-13

but when pulling cluster resources it's ok
Capture d’écran du 2024-02-21 14-57-28

**Comment by sbouchet** [comment]
still does not work as expected on fedora
[Capture vidéo du 2024-02-22 09-56-44.webm](https://github.com/redhat-developer/intellij-kubernetes/assets/600414/15a5c328-4ba2-4581-8af0-a510326a2b04)

**Comment by datho7561** [comment]
Multiline editing now works properly for me.

One more thing I ran into was if you have a single line secret, and try to insert a newline, then it won't work. However, I don't think this is a big issue.

**Comment by adietish** [comment]
@datho7561, @sbouchet: I fixed both issues. One can now edit quoted values and you can insert new lines by pressing Shift + Enter. An explanatory label to the left of the balloon would tell you about it. Enter alone applies the value. I dont provide different views (text field / text area) any more. I always use a text area with at least 3 rows. I noticed that this distinction doesnt make a lot of sense when you start turning a short value to a multi-line value (ex 42 -> big certificate).
I also enabled word wrapping so that the input balloon always has the same width.
image

**Review by datho7561 — APPROVED** [review]
Looks great to me!

**Review by datho7561 — APPROVED** [review]
Still seems good to me!

**Pull request merged**
