### PR TITLE
impl'd terminal&log sessions independent of context (#511)

### LINKED ISSUE #511: Terminal: should stay operational even if I switch the current namespace
**Steps:**
1. EXEC: have a terminal to a pod
2. EXEC: switch the current namespace

**Result:**
Terminal freezes

### PR DESCRIPTION
**Pull request by adietish**
fixes #511

### CODE REVIEW

**Comment by adietish** [comment]
There's 1 usecase that doesn't work yet:

**Steps:**
1. ASSERT: have 2 contexts: 
  * Red Hat sandbox where your token is expired
  * minikube
2. ASSERT: have a pod running on minikube
3. ASSERT: have minikube as current context
4. EXEC: open a terminal to the pod in minikube
5. EXEC: switch the current context to the Red Hat sandbox

**Result:**
Terminal is freezing. You have to close and open a fresh terminal. The exception that is thrown is 
`java.net.SocketTimeoutException: sent ping but didn't receive pong within 30000ms (after 0 successful ping/pongs)`



If you have a valid token to the sandbox everything works fine. The terminal stays functional.

**Comment by adietish** [comment]
Odd, I now cannot reproduce it any more.

The current implementation should not process anything when the change in the kubeconfig file happens: 
When setting the users set the current context, the plugin updates the kubeconfig file. The update happens async in a thread:
AllContexts
```kotlin
	private fun recreateClient(namespace: String?, context: String?, client: ClientAdapter<out KubernetesClient>?)
			: ClientAdapter<out KubernetesClient> {
		client?.close()
		val new = clientFactory.invoke(namespace, context)
---->		new.config.save()
		this.client.set(new)
		return new
	}
```

The change in file then invokes `AllContexts.onKubeConfigChanged`. This method, that is always invoked when the kubeconfig file changes, then should not do anything because it sees that the kubeconfig file and the client config match in 
* current context
* all contexts
* token

AllContexts
```kotlin
	protected open fun onKubeConfigChanged(fileConfig: io.fabric8.kubernetes.api.model.Config) {
		val client = client.get() ?: return
		val clientConfig = client.config.configuration
--->		if (ConfigHelper.areEqual(fileConfig, clientConfig)) {
			return
		}
		client.close()
		this.client.reset() // create new client when accessed
		refresh()
	}
```

**Comment by adietish** [comment]
Fixed the following usecase: 
**Steps:**
1. EXEC: have a pod running & a terminal for it
2. EXEC: delete the pod
**Result (before)**:
Terminal is freezing as soon as the pod disappears

**Result (now):**
An error in the terminal tab is shown
image

**Comment by adietish** [comment]
I dont see how I can get informed of the connection being closed for logs. For terminals I can provide a listener that gets called whenever the connection is closed. This doesn't exist for logs.

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: this is ready for testing. #502 still exists and may get fixed automatically when using client v6. I'll fix/add unit tests while you're testing this.

**Review by lstocchi — APPROVED** [review]
LGTM, as you said i didn't consider this https://github.com/redhat-developer/intellij-kubernetes/issues/502

**Comment by lstocchi** [comment]
A sec maybe i found something when switching namespace on same cluster

**Review by lstocchi — CHANGES_REQUESTED** [review]
Sorry for coming up with an issue after giving my LGTM.... I did my tests by using two different clusters but then it came to my mind i didn't test it by switching namespaces on the same cluster.

It looks to me that when i switch namespace the terminal&log session are still bind to the old ns.
What i do:
1) i'm connected to the default ns on my minikube cluster
2) i open the terminal and logs tabs of one pod
3) everything works fine
4) i switch namespace
5) i try to open the terminal and logs tab of a pod that only exists in this namespace (and not in default - be sure because you may have a resource with the same name on the default ns and the behavior may seem correct)
6) the terminal tab shows the error `it cannot connect` and the log tab a message like `"pods \"nginx-8\" not found"` but the pod exists and it's reachable 
7) i have the impression that it still looks at the default namespace even if i switched

**Comment by adietish** [comment]
@lstocchi Thanks for spotting this. I found and fixed the problem. Please re-test.

**Review by lstocchi — APPROVED** [review]

**Pull request merged**
