### PR TITLE
impl'd action to open a terminal in pods (#214)

### LINKED ISSUE #214: As a user I want to be able to open a terminal in a pod
related to #215 

A user reported why he liked jetbrains kubernetes plugin with the following:
> It has even a nice "run shell inside the pod" feature (which of course doesn't work for containers without a shell, like the distroless builds done by ko)

### PR DESCRIPTION
**Pull request by adietish**
fixes #214, #461

### CODE REVIEW

**Comment by adietish** [comment]
among the things that are possibly missing is closing the terminal connection when the active context (current user, cluster, namespace) is changed. Will have to verify how vscode behaves and to the same.

**Comment by adietish** [comment]
@lstocchi, @jeffmaury  do you want to test it and provide feedback on usability, please? 
Current impl has a combobox in the toolbar that displays the current container and allows to switch it. The alternative would be to have the containers in the context menu like jetbrains does (see https://github.com/redhat-developer/intellij-kubernetes/issues/461#issuecomment-1192755669).

**Comment by jeffmaury** [comment]
When you switch to a container the terminal from the current window is lost which is not happening on VSCode
ijk

**Comment by adietish** [comment]
> When you switch to a container the terminal from the current window is lost which is not happening on VSCode

So you would want selecting an item in the combobox to open a new tab (if it doesn't exist) rather than switch within the same terminal, correct?

**Comment by adietish** [comment]
> When you switch to a container the terminal from the current window is lost which is not happening on VSCode 
You want both terminals to exist while only the selected one would be visible, correct?

**Comment by adietish** [comment]
@jeffmaury replaced the combobox in the terminals by submenu items for "Follow Logs" and "Terminal"
grafik
Want to give it a try usability wise?

**Comment by lstocchi** [comment]
@adietish tried with the submenu items. Looks good to me. It is possible to hide the submenu if there is only one container?
Then i would add the name of the pod in the terminal tab, otherwise i have no clue what container i'm looking at
image

**Comment by lstocchi** [comment]
> IMHO this then bears the following benefit: to open a new terminal to a different container you dont have to get back to the tree. You can switch right where you're are, next to your terminal. Makes sense?

I didn't get this part. 
So you don't show the containers in the submenu anymore. When you click on the pod (POD1) i suppose it starts following logs from the first container, then on the right there will be a panel that show all containers belonging to the POD1, right?
If so, when you follow another pod (say POD2), in the right panel you will see the containers belonging only to POD2? Or a mix of POD1 and POD2?

**Comment by adietish** [comment]
@lstocchi:
> I didn't get this part. So you don't show the containers in the submenu anymore. When you click on the pod (POD1) i suppose it starts following logs from the first container, then on the right there will be a panel that show all containers belonging to the POD1, right?
Exactly. I just plan to have the list of containers on the left as this seems more common in IDEA.
> If so, when you follow another pod (say POD2), in the right panel you will see the containers belonging only to POD2? Or a mix of POD1 and POD2?
Each pod would have it's on tab. The list within the tab holds the containers for this pod. It's similar to the solution with the comboxbox but with a list and terminal widgets for each container. We're not reusing a terminals which lead to loosing the prior output/history.
Makes sense?

**Comment by lstocchi** [comment]
> Each pod would have it's on tab. The list within the tab holds the containers for this pod. It's similar to the solution with the comboxbox but with a list and terminal widgets for each container. So there's no mixing of the containers for POD1 and POD2. The tab that was opened for POD1 will list the containers within POD1. POD2 would have it's own tab. We're not reusing a terminals which lead to loosing the prior output/history. Makes sense?

Yes, ok. I still think that having the submenu could have some value. Look forward to see how it works this way  :+1:

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: the basics of the new approach are working. Please give it a try and give me feedback on your preference (submenu items or containers list in the terminal view). Thanks.

**Comment by jeffmaury** [comment]
LGTM with the following remark: the shell are displayed in the Kubernetes logs window which may be confusing.

**Comment by adietish** [comment]
> LGTM with the following remark: the shell are displayed in the Kubernetes logs window which may be confusing.

Before merging I need to fix the unit tests and correct "Kubernetes Logs" to "Kubernetes Consoles" as you pointer out.

**Comment by lstocchi** [comment]
LGTM, simple and clean solution. :+1: 

Faced a critical error when trying to open the terminal in a container which is not running
```
Exec Failure

io.fabric8.kubernetes.client.http.WebSocketHandshakeException
	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onFailure(OkHttpWebSocketImpl.java:66)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:169)
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:180)
		at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:332)
		at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:85)
		at com.redhat.devtools.intellij.kubernetes.model.resource.ExecWatcher.watch(ExecWatcher.kt:38)
		at com.redhat.devtools.intellij.kubernetes.model.resource.NamespacedResourceOperator.watchExec(NamespacedResourceOperator.kt:109)
		at com.redhat.devtools.intellij.kubernetes.model.resource.kubernetes.NamespacedPodsOperator.watchExec(NamespacedPodsOperator.kt:42)
		at com.redhat.devtools.intellij.kubernetes.model.resource.kubernetes.NamespacedPodsOperator.watchExec(NamespacedPodsOperator.kt:26)
		at com.redhat.devtools.intellij.kubernetes.model.context.ActiveContext.watchExec(ActiveContext.kt:350)
		at com.redhat.devtools.intellij.kubernetes.model.ResourceModel.watchExec(ResourceModel.kt:215)
		at com.redhat.devtools.intellij.kubernetes.console.TerminalTab.createExecWatch(TerminalTab.kt:69)
		at com.redhat.devtools.intellij.kubernetes.console.TerminalTab.startWatch(TerminalTab.kt:35)
		at com.redhat.devtools.intellij.kubernetes.console.TerminalTab.startWatch(TerminalTab.kt:27)
		at com.redhat.devtools.intellij.kubernetes.console.ConsoleTab$ConsolesPanel$create$$inlined$runAsync$1.run(promise.kt:402)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
		... 1 more
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	... 5 more
```

**Comment by adietish** [comment]
@lstocchi filed this problem to a separate issue because the solution is not obvious. It happens in a threadpool and bubbles up to the IDE: #502 

> Faced a critical error when trying to open the terminal in a container which is not running
>
> Exec Failure
> 
> io.fabric8.kubernetes.client.http.WebSocketHandshakeException
> 	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onFailure(OkHttpWebSocketImpl.java:66)

**Comment by adietish** [comment]
> Faced a critical error when trying to open the terminal in a container which is not running
> 
> ```
> Exec Failure
> 
> io.fabric8.kubernetes.client.http.WebSocketHandshakeException
> 	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onFailure(OkHttpWebSocketImpl.java:66)

I filed this to #502

**Review by lstocchi — CHANGES_REQUESTED** [review]
Works fine with a container but i found it not intuitive at first. 
I selected a pod with a container and clicked on `terminal` and faced this
image

I was expecting a terminal to be opened automatically, but i needed to click on nginx.
Is it possible to open it by default?
When working with multiple containers it makes sense such a behavior but ...  wouldn't it be better to add a message on the right panel? Similar to what IJ does in other features like
image

of course, instead of `nothing to show` you could write `select a container from the list on the left` ?

**Comment by adietish** [comment]
> I was expecting a terminal to be opened automatically, but i needed to click on nginx. Is it possible to open it by default? 

@lstocchi thanks for spotting this. It should not happen, the first container should be selected by default. Need to figure out why this happens for you.

**Comment by adietish** [comment]
@lstocchi, @jeffmaury: the 1st container is selected by default when you open a terminal. 
I would like to fix #502, too before releasing.

**Comment by adietish** [comment]
I filed a shortcoming in this PR that @jeffmaury found (https://github.com/redhat-developer/intellij-kubernetes/issues/502#issuecomment-1290580313) is that one cannot reconnect to containers that were not ready yet. I filed this to #509

**Comment by adietish** [comment]
@lstocchi can you please review this? This is a prerequisite to #214

**Review by lstocchi — CHANGES_REQUESTED** [review]
If i open a terminal tab on a pod and then I change namespace, this critical error pops up.
It also happens if i close the terminal tab before switching.

Maybe we could close all tabs when switching namespace? :thinking: 
```
Exec Failure

javax.net.ssl.SSLException: Socket closed
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1581)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:979)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:68)
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.net.SocketException: Socket closed
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
		... 18 more
Caused by: java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1354)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:963)
	... 14 more
```

**Comment by adietish** [comment]
@lstocchi: thanks for testing and reporting this.

> If i open a terminal tab on a pod and then I change namespace, this critical error pops up. It also happens if i close the terminal tab before switching.
> 
> Maybe we should close all tabs when switching namespace? 🤔
> 

I had verified what vscode does and they dont close the tabs, they report the error. Ideally we should also do the same as should happen with #214 in place. I'll verify it.

**Review by lstocchi — APPROVED** [review]
> In this PR a fatal IDE error is displayed and the terminal is freezing. The fatal IDE error is what I try to fix in #502. An error should be displayed within the terminal (tab) as in #509. Keeping the terminal operational is filed to #511. In this sense I would consider this PR as good enough and try to tackle the issues in #502, #509, #511. Agree?
> In this PR a fatal IDE error is displayed and the terminal is freezing. The fatal IDE error is what I try to fix in #502. An error should be displayed within the terminal (tab) as in #509. Keeping the terminal operational is filed to #511. In this sense I would consider this PR as good enough and try to tackle the issues in #502, #509, #511. Agree?

Sure, as you prefer. For the rest LGTM

**Pull request merged**
