### PR TITLE
editor: serialize yaml without quotes where possible (#310)

### LINKED ISSUE #310: String values in yaml should not be quoted if not required
taken from https://github.com/redhat-developer/intellij-kubernetes/issues/307#issuecomment-980537056

**Steps:**
1. ASSERT: have a pod running
2. EXEC: open pod in editor
ex. 
```
---
apiVersion: "v1"
kind: "Pod"
metadata:
  creationTimestamp: "2021-11-16T18:26:52Z"
  generateName: "mehdb-"
  labels:
    app: "mehdb"
    controller-revision-hash: "mehdb-9b596f6c9"
    statefulset.kubernetes.io/pod-name: "mehdb-0"
    ...
```
3. EXEC: retrieve the same pod with kubectl `kubectl get pod <name>`
ex.
``` 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-16T18:26:52Z"
  generateName: mehdb-
  labels:
    app: mehdb
    controller-revision-hash: mehdb-9b596f6c9
    statefulset.kubernetes.io/pod-name: mehdb-0
```
4. EXEC: compare `kind:`

**Result:**
The plugin displays `kind: "Pod"` whereas kubectl is showing `kind: Pod`

### PR DESCRIPTION
**Pull request by adietish**
fixes #310

### CODE REVIEW

**Comment by adietish** [comment]
I'm using my own mapper currently, will PR the client to allow additional configurations for it.

**Comment by adietish** [comment]
@olkornii the ITs are failing here. I dont see what's wrong just by reading the code and can't help since I can't run them on Mac. This PR removes the quotes from values in YAML where they're not required (see #314). Maybe investing some time to have the ITs running on Mac would allow you to unload some of these fixing tasks to me.

**Comment by lstocchi** [comment]
Quite annoying you can't run it on Mac :/ BTW if you need help or don't have enough time, ping me, i'm on linux

**Comment by adietish** [comment]
> Quite annoying you can't run it on Mac :/ BTW if you need help or don't have enough time, ping me, i'm on linux

@lstocchi: sure, if you could give it a try reviewing it, that would be awesome.

**Comment by adietish** [comment]
this PR is causing an error when pushin a node the following node on CRC:
```
---
apiVersion: v1
kind: Node
metadata:
  annotations:
    machine.openshift.io/machine: openshift-machine-api/crc-ktfxm-master-0
    machineconfiguration.openshift.io/controlPlaneTopology: SingleReplica
    machineconfiguration.openshift.io/currentConfig: rendered-master-372f2b4ac6ef4313babf589fb43ac930
    machineconfiguration.openshift.io/desiredConfig: rendered-master-372f2b4ac6ef4313babf589fb43ac930
    machineconfiguration.openshift.io/reason: ""
    machineconfiguration.openshift.io/ssh: accessed
    machineconfiguration.openshift.io/state: Done
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2021-11-07T04:36:05Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    jedi: anakin
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: crc-ktfxm-master-0
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
    node-role.kubernetes.io/worker: ""
    node.openshift.io/os_id: rhcos
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          ".": {}
          f:volumes.kubernetes.io/controller-managed-attach-detach: {}
        f:labels:
          ".": {}
          f:beta.kubernetes.io/arch: {}
          f:beta.kubernetes.io/os: {}
          f:kubernetes.io/arch: {}
          f:kubernetes.io/hostname: {}
          f:kubernetes.io/os: {}
          f:node-role.kubernetes.io/master: {}
          f:node.openshift.io/os_id: {}
    manager: kubelet
    operation: Update
    time: 2021-11-07T04:36:05Z
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:machine.openshift.io/machine: {}
    manager: nodelink-controller
    operation: Update
    time: 2021-11-07T04:50:12Z
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:machineconfiguration.openshift.io/currentConfig: {}
          f:machineconfiguration.openshift.io/reason: {}
          f:machineconfiguration.openshift.io/ssh: {}
          f:machineconfiguration.openshift.io/state: {}
    manager: machine-config-daemon
    operation: Update
    time: 2021-11-08T05:49:37Z
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:allocatable:
          f:cpu: {}
          f:ephemeral-storage: {}
          f:memory: {}
        f:capacity:
          f:cpu: {}
          f:ephemeral-storage: {}
          f:memory: {}
        f:conditions:
          k:{"type":"DiskPressure"}:
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
          k:{"type":"MemoryPressure"}:
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
          k:{"type":"PIDPressure"}:
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
          k:{"type":"Ready"}:
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
        f:images: {}
        f:nodeInfo:
          f:bootID: {}
          f:systemUUID: {}
    manager: kubelet
    operation: Update
    time: 2021-12-07T15:11:42Z
    subresource: status
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:machineconfiguration.openshift.io/controlPlaneTopology: {}
          f:machineconfiguration.openshift.io/desiredConfig: {}
        f:labels:
          f:node-role.kubernetes.io/worker: {}
    manager: machine-config-controller
    operation: Update
    time: 2021-12-07T15:12:22Z
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:jedi: {}
    manager: okhttp
    operation: Update
    time: 2021-12-07T15:43:46Z
  name: crc-ktfxm-master-0
  resourceVersion: 44291
  uid: 8816fd05-11f0-40c5-9d7c-b248bc7fee83
spec: {}
status:
  addresses:
  - address: 192.168.126.11
    type: InternalIP
  - address: crc-ktfxm-master-0
    type: Hostname
  allocatable:
    cpu: 3800m
    ephemeral-storage: 29463813686
    hugepages-1Gi: 0
    hugepages-2Mi: 0
    memory: 8723360Ki
    pods: 250
  capacity:
    cpu: 4
    ephemeral-storage: 31970284Ki
    hugepages-1Gi: 0
    hugepages-2Mi: 0
    memory: 9184160Ki
    pods: 250
  conditions:
  - lastHeartbeatTime: 2021-12-07T15:54:52Z
    lastTransitionTime: 2021-12-07T15:11:42Z
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: 2021-12-07T15:54:52Z
    lastTransitionTime: 2021-12-07T15:11:42Z
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: 2021-12-07T15:54:52Z
    lastTransitionTime: 2021-12-07T15:11:42Z
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: 2021-12-07T15:54:52Z
    lastTransitionTime: 2021-12-07T15:11:42Z
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d0697338e6d3304ef1efd92e5d3740f6b519f2918aaa1a7a5df31cf7f8482145
    sizeBytes: 1144505189
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:24a66633e8b6ebc1b95af3fbd0f172f85043dfb2dec5f5e13c582cc9241b1ea0
    sizeBytes: 769444015
  - names:
    - registry.redhat.io/redhat/redhat-operator-index@sha256:2c62a0bef369b3a6832875397f27938fcf929c5658554662b7c5f4ea7b4e3071
    - registry.redhat.io/redhat/redhat-operator-index@sha256:8038c3fafac35d66119249a7f3cbc7084fc28815272cda481e6c0ed53c4949d0
    - registry.redhat.io/redhat/redhat-operator-index:v4.9
    sizeBytes: 695440393
  - names:
    - registry.redhat.io/redhat/redhat-operator-index@sha256:1efaca77a77997a94138709f4ad35bdddc96ae5158ebf8d776ea24efda567df2
    sizeBytes: 695399442
  - names:
    - registry.redhat.io/redhat/redhat-operator-index@sha256:d4cc163ce7387721f6bf9e705931717590ab0991e326b063388eb7b8a0075ff5
    sizeBytes: 685955611
  - names:
    - registry.redhat.io/redhat/community-operator-index@sha256:72b24363447463ac0349ad4f7bfe1414820aa7408d492fa9c17987144ccc7303
    - registry.redhat.io/redhat/community-operator-index@sha256:b206c756738207d20f38aaf236e90b3ca7326e29def3c33fda481f1260b0ff1f
    - registry.redhat.io/redhat/community-operator-index:v4.9
    sizeBytes: 681377859
  - names:
    - registry.redhat.io/redhat/community-operator-index@sha256:31310ce34c8f945bd880cef62160f6c3d87c80104a26180efac6c3c7538bae06
    sizeBytes: 677279099
  - names:
    - registry.redhat.io/redhat/certified-operator-index@sha256:8e5b4cd22b161cf59fd22579ac3f6168087823ba0782a4d03000f72e4465ad45
    - registry.redhat.io/redhat/certified-operator-index@sha256:9fbfa1a24a3ab6770b20750d92e3167294c6fc87c8259169f7cfd15c7a6ca339
    - registry.redhat.io/redhat/certified-operator-index:v4.9
    sizeBytes: 675395972
  - names:
    - registry.redhat.io/redhat/certified-operator-index@sha256:369cd11e04e396737bdabc4f93594579d533db7d89014c7e1e004272ae23d40c
    sizeBytes: 671534996
  - names:
    - registry.redhat.io/redhat/redhat-marketplace-index@sha256:ea3fb019771ac032275adfc127bf921ea163ae50f5e979054cad5f66294a6f4f
    - registry.redhat.io/redhat/redhat-marketplace-index@sha256:ed7c48954c0e0e96ae2197310366f8ce7d82a5fd1426b730ed2649dfd312e6e6
    - registry.redhat.io/redhat/redhat-marketplace-index:v4.9
    sizeBytes: 668092793
  - names:
    - registry.redhat.io/redhat/redhat-marketplace-index@sha256:bdc89d4422babaf92f884b2082a03668899dbe1415f5093cc7ef70b9901a9e0d
    sizeBytes: 667986301
  - names:
    - registry.redhat.io/redhat/redhat-marketplace-index@sha256:f85e69ac69860c6ac11f53f919854a98fe523b30db7f2ece8a26c51ca84be73d
    sizeBytes: 667852677
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ca24e6680fb35b4145d5338e1e401f1227e919bc0709a31804fb04f8a7dfc163
    sizeBytes: 619136130
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:20a23703ed05f9b02b012f023a3e0239739cec66db60fd814cc6ab15b1adfa51
    sizeBytes: 575472561
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f6bd6f970babbb1d2d362b1ae10d9b22cacef0db5ca8e1e650b8bb3adbee8bfc
    sizeBytes: 571277850
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:09f6713e0a0325027b99ee73e7d9126428644bf58dad7d8cb565c9e96b66f042
    sizeBytes: 520601191
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:472795c686b7aa5863b17525ad2a05baa0713f298572b65ba0d396f48f34b936
    sizeBytes: 464490239
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9881b33906a93aa84a626388e64d126855282a906881eb9b499e181a656a0775
    sizeBytes: 451347092
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b6b62378198c10353bd6a5893f6fc4e85742b84ed0cadce5b57eccc02cba2014
    sizeBytes: 451237505
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2f1e81873bc63c289e01a19fcc18a8f56ebcd26e60659744d4d2c5875f00b403
    sizeBytes: 420168901
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1691d520a978f5b99a67f2aae9fd40ec62d31c2f7cb97d0a83c51ca05cca69e7
    sizeBytes: 419813543
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8ec26f8ab5fbf17723d734a67faf8f8ae35c97e9e2e599686c00c6e70a6f416e
    sizeBytes: 415608406
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e40c49f22c80e07628d663155f3788398dd083d819e25dfde8728f8a75ebe4af
    sizeBytes: 410230425
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9d50b7be7e5bd9833a14682c5c9e7dd00d159f91ce2e140372889c4e195722b1
    sizeBytes: 401467275
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e12354bf29c3098ecc12fd7827368a0fd197acbe46380e41af7647f7097ef931
    sizeBytes: 398505215
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5ffab8f388eee8133db5b00ff1ab941d33b5a9172a70713a6bd33af22225a20c
    sizeBytes: 387506547
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:65bee19e43856b64e0bd34e12e44967fc22e3feadec014d92993480698a6bf1a
    sizeBytes: 387183209
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a73737e106cc98dce1ea70b1e44772feb8885b18a5196156ad034f0f2ea3d440
    sizeBytes: 378179095
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3bc42020e6c42a552948a364f9dd783afa5a9b137bf424ef22947e186a748289
    sizeBytes: 377423384
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3423de1bf46bb207e64b0a87559383ca423bd3536d7091740cf2c714613b7ace
    sizeBytes: 376324707
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b4548a4f668991cfd6cee5bbbb816b15faece2b0f25b8815665a96934912e051
    sizeBytes: 375357061
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08a112fcc0230919dacf6ea7c88f68a7999c526477d8a8f0451c85f6bb25a95c
    sizeBytes: 374431906
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:09ab9cd3325521de41b40e1e0323cfb29aa53d52058e0be716bbf9d45982c368
    sizeBytes: 372270700
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6ef8f961f0583517c190be55b62bc0b8d58fec1b648bc98d6d10143e79f38f5e
    sizeBytes: 372009050
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:76c30cd3ffb9a73d78e17b02712d512fec28fa1e1c83db876c01979807b8353c
    sizeBytes: 371719364
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ef595a6794b7c3ce9a966ceb14903fc44012c20fdef5622b32d4608df36f7809
    sizeBytes: 371693604
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:81431b443d62f15f690330942431a2b108e982cf47c1649205dfa11dd2bad904
    sizeBytes: 371450931
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:db8d8c0a6b9d0c763f9835e68cc1f05981b0a2cefad03c84bebf533e7c256fb2
    sizeBytes: 370447426
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:22cab10687a9da592ab27fb20efbe72d288d87a6a974afed14da324fbb2b4bbd
    sizeBytes: 369290355
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2d6396555aa5265dc6024269644376e320f76a5242ca5b5c21048be4f4cd2768
    sizeBytes: 369249426
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b213e55d05c9dc078b5701a7b381cb2d4c5cd5a831ca118e3d5335cd0133a3b5
    sizeBytes: 368566716
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7f7cda8b40adbe1dc3632edd98894949f5049f55b21abacfb76fbba8dd23f9cb
    sizeBytes: 367669976
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cebaea9de8e30add43caddb7158a5da9ac93bdcda2e17352929cbdcdc7b7b07b
    sizeBytes: 367617056
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9325c2c30cf01d042c880d80f54a6abe971d98593933bf57416ed5a4819e4aed
    sizeBytes: 363889118
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d9ddd1836b096fb5ea77cf3f43d5d172658647df624d3c81165f116dfd7a61c2
    sizeBytes: 358047100
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c9ff18f90a6ca9431655a6dd0fb91fbd069c5f587d708d0b5ad86597cb47531
    sizeBytes: 357148588
  - names:
    - quay.io/openshift-release-dev/ocp-release@sha256:386f4e08c48d01e0c73d294a88bb64fac3284d1d16a5b8938deb3b8699825a88
    sizeBytes: 354083145
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ec368d480b14b294cb49dbba6819c2d2421ef0f57d4a0d2b2761db30736383c6
    sizeBytes: 350084637
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8e53d991b27687214ced939b201ec92dcf4e77a1c812996b385924a898d3d950
    sizeBytes: 344562806
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:54816af3c8b44750061a891d0c32ce8125a8aeaa0248f6308a6f94381d53b070
    sizeBytes: 339287587
  nodeInfo:
    architecture: amd64
    bootID: 702c3430-d2db-4678-bed8-87960cc3b48f
    containerRuntimeVersion: cri-o://1.22.0-74.rhaos4.9.gitd745cab.el8
    kernelVersion: 4.18.0-305.19.1.el8_4.x86_64
    kubeProxyVersion: v1.22.0-rc.0+a44d0f0
    kubeletVersion: v1.22.0-rc.0+a44d0f0
    machineID: b2492b0b3eeb4c048882552ee1ab523c
    operatingSystem: linux
    osImage: Red Hat Enterprise Linux CoreOS 49.84.202110220538-0 (Ootpa)
    systemUUID: c3d611ea-0000-0000-9fd7-f2189899ab08

```
Error:
```
Error Pushing: Could not push Node crc-ktfxm-master-0 to cluster: Node in version “v1” cannot be handled as a Node: v1.Node.ObjectMeta: v1.ObjectMeta.Labels: CreationTimestamp: unmarshalerDecoder: parsing time “1636259765000" as “2006-01-02T15:04:05Z07:00”: cannot parse “259765000" as “-”, error found in #10 byte of ...|259765000",“labels”:|..., bigger conte...}).
```

**Comment by adietish** [comment]
@lstocchi turns out that the reason for this error is that ex. all timestamps in the kubernetes-client objects are strings:
```java
public class ManagedFieldsEntry implements KubernetesResource
{
    ...
    @JsonProperty("time")
    private String time;
```
or
```java
public class ObjectMeta implements KubernetesResource
{
    ...
    @JsonProperty("creationTimestamp")
    private String creationTimestamp;
```

**Comment by lstocchi** [comment]
> @lstocchi turns out that the reason for this error is that ex. all timestamps in the kubernetes-client objects are strings:

Yeah they followed types used in k8s schemas. If you look at the pod schema you will see the difference. When it deals with datetimes, the only thing that changes from a "normal" string is its format. (below `clusterName` is a normal string field, `creationTimestamp` a datetime string field)

```
"clusterName": {
          "description": "The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request.",
          "type": [
            "string",
            "null"
          ]
        },
        "creationTimestamp": {
          "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
          "format": "date-time",
          "type": [
            "string",
            "null"
          ]
        },
```

The only way i can think to overcome this is to take the date-time fields from the corresponding schema and then using a custom serializer to change jackson behavior

```
class DateTimeSerializer extends StdSerializer<String> {

    protected DateTimeSerializer() {
        super(String.class);
    }

    @Override
    public void serialize(String s, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
        if(isDateTime) { 
          jsonGenerator.writeString("\"" + s + "\"");
        }
    }
}
``` 

WDYT? Any other way to solve this?

**Comment by adietish** [comment]
We decided to drop the requirement for this change, see https://github.com/redhat-developer/intellij-kubernetes/issues/310#issuecomment-992358063. Closing without merging.

**Pull request closed without merging**
