### PR TITLE
show config maps and secrets (#61)

### LINKED ISSUE #61: subtask to #35: show "Configuration"
depends on #35 

here's how things look in vscode:
image

### PR DESCRIPTION
**Pull request by adietish**
fixes #61

### CODE REVIEW

**Comment by adietish** [comment]
here's how configurations are displayed with this PR:
image
Here's in comparison how vscode is displaying them:
image

**Comment by adietish** [comment]
> This PR is not only about secrets resources but also about Endpoints (from #59) and Storage (#62)

that's because this depends on the prior PRs. Once these are merged, this should come clean.

**Comment by jeffmaury** [comment]
That makes it hard to review as most of the code in this PR has no relation at all with the feature implemented. Don't understand why those PR are linked

**Comment by adietish** [comment]
> That makes it hard to review as most of the code in this PR has no relation at all with the feature implemented. Don't understand why those PR are linked

I simply move on implementing features for issues and simplify/change things when working on the issue (ex. when providing pod icons, I had to move from Icons to a method overload that provides the icon). Those changes are of course filed to their own commits within a PR. That's why the sequence of PRs matters.

**Comment by adietish** [comment]
this PR depends on #60 and should thus be reviewed and merged after #60 was reviewed and merged.

**Comment by adietish** [comment]
@jeffmaury rebased and separated from other PRs, please re-review

**Pull request merged**
