### PR TITLE
also list init containers in terminal-/log-tabs (#523)

### LINKED ISSUE #523: Support init containers
According to the [docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) init containers are specialized containers that run before app containers in a [Pod](https://kubernetes.io/docs/concepts/workloads/pods/). Init containers can contain utilities or setup scripts not present in an app image.

The OpenShift docs are at https://docs.openshift.com/container-platform/4.11/nodes/containers/nodes-containers-init.html

In the reviews to the jetbrains plugin there are several people requesting support for init container:
* https://plugins.jetbrains.com/plugin/10485-kubernetes/reviews#review=74755 image
* https://plugins.jetbrains.com/plugin/10485-kubernetes/reviews#review=74758 image

### PR DESCRIPTION
**Pull request by adietish**
fixes #523

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: please review. 
* There's a minor issue left that I cannot fix but hope to get fixed when moving to kubernetes-client v6: ["Follow Logs" for a container that's waiting will print error response into the console](https://github.com/redhat-developer/intellij-kubernetes/issues/534)

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by jeffmaury** [comment]
Use this pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: registry.access.redhat.com/ubi8/ubi:latest
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
    - name: init-myservice
      image: registry.access.redhat.com/ubi8/ubi:latest
      command: ['sh', '-c', 'for i in {1..10}; do echo First waiting for $i; sleep 2; done;']
    - name: init-mydb
      image: registry.access.redhat.com/ubi8/ubi:latest
      command: ['sh', '-c', 'for i in {1..10}; do echo Second waiting for $i; sleep 2; done;']
```

But once the first init container is terminated, I was never able to see the log for the second one so not LGTM 🥲

**Comment by adietish** [comment]
@jeffmaury investigating, filing a new issue if I can reproduce.

**Pull request merged**
