### PR TITLE
display custom resources in the version that has the highest priority (#117)

### LINKED ISSUE #117: Should display the custom resources in the version that has the highest priority
steps:
1. ASSERT: make sure you have a crd with different versions:
```
echo "apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cars.openshift.pub
spec:
  group: openshift.pub
  names:
    kind: Car
    listKind: CarList
    plural: cars
    singular: car
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1beta1
    served: true
    storage: true
  names:
    kind: Car
    plural: cars" | kubectl apply -f - 
```
2. ASSERT: make sure that you custom resources in all versions that are defined in the custom resource definition:
```
echo "apiVersion: openshift.pub/v1alpha1
kind: Car
metadata:
  name: bmw
spec:
  date_of_manufacturing: "2014-07-01T00:00:00Z"
  engine: N57D30" | kubectl apply -f -
```
```
echo "apiVersion: openshift.pub/v1beta1
kind: Car
metadata:
  name: bmw
spec:
  date_of_manufacturing: "2014-07-01T00:00:00Z"
  engine: N57D31" | kubectl apply -f -
```
3. EXEC: launch the plugin and look into "Custom Resources" > cars what the decoration is telling you about the version that is displayed

Result:
`v1alpha1` cars are displayed
image

Expected result:
`v1beta1` resources are displayed

### PR DESCRIPTION
**Pull request by adietish**
fixes #117

### CODE REVIEW

**Comment by adietish** [comment]
this PR is in java on purpose. I want this to be merged into kubernetes-client, keeping it here as long as the client with it is not published.

**Comment by adietish** [comment]
The code is submitted as PR for the kubernetes-client at https://github.com/fabric8io/kubernetes-client/pull/2601

**Comment by adietish** [comment]
@lstocchi this PR makes sure that the version with the highest priority is displayed. Dare to test it please?

**Review by lstocchi — CHANGES_REQUESTED** [review]
Everything looks good but i still face the error. If I add `spec.version = version` to your function, it works fine 
```
fun create(spec: CustomResourceDefinitionSpec): ResourceKind<GenericResource> {
			val version = getVersion(spec.versions) ?: spec.version
			spec.version = version
			return ResourceKind(
				removeK8sio(getApiVersion(spec.group, version)),
				GenericResource::class.java,
				spec.names.kind)
		}
```

The problem is that the k8s client returns the crd object with the version already set to v1alpha even if in my cluster there is no trace of this.

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines","pipeline.tekton.dev/release":"v0.16.3","version":"v0.16.3"},"name":"pipelines.tekton.dev"},"spec":{"conversion":{"strategy":"Webhook","webhookClientConfig":{"service":{"name":"tekton-pipelines-webhook","namespace":"tekton-pipelines"}}},"group":"tekton.dev","names":{"categories":["tekton","tekton-pipelines"],"kind":"Pipeline","plural":"pipelines"},"preserveUnknownFields":false,"scope":"Namespaced","subresources":{"status":{}},"validation":{"openAPIV3Schema":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"versions":[{"name":"v1alpha1","served":true,"storage":false},{"name":"v1beta1","served":true,"storage":true}]}}
  creationTimestamp: "2020-09-17T09:57:44Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: v0.16.3
    version: v0.16.3
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:conditions: {}
    manager: kube-apiserver
    operation: Update
    time: "2020-09-17T09:57:44Z"
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/part-of: {}
          f:pipeline.tekton.dev/release: {}
          f:version: {}
      f:spec:
        f:conversion:
          .: {}
          f:conversionReviewVersions: {}
          f:strategy: {}
          f:webhookClientConfig:
            .: {}
            f:service:
              .: {}
              f:name: {}
              f:namespace: {}
              f:port: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:preserveUnknownFields: {}
        f:scope: {}
        f:subresources:
          .: {}
          f:status: {}
        f:validation:
          .: {}
          f:openAPIV3Schema:
            .: {}
            f:type: {}
            f:x-kubernetes-preserve-unknown-fields: {}
        f:version: {}
        f:versions: {}
      f:status:
        f:storedVersions: {}
    manager: oc
    operation: Update
    time: "2020-09-17T09:57:44Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          f:webhook:
            f:clientConfig:
              f:caBundle: {}
              f:service:
                f:path: {}
    manager: webhook
    operation: Update
    time: "2020-09-17T09:58:34Z"
  name: pipelines.tekton.dev
  resourceVersion: "259600"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/pipelines.tekton.dev
  uid: 095acf81-4152-4396-9866-d88a8f3c9737
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVLekNDQXhPZ0F3SUJBZ0lSQU1UMVVMSnNNUUhvVkJad2YxRVppSUl3RFFZSktvWklodmNOQVFFTEJRQXcKVGpFVU1CSUdBMVVFQ2hNTGEyNWhkR2wyWlM1a1pYWXhOakEwQmdOVkJBTVRMWFJsYTNSdmJpMXdhWEJsYkdsdQpaWE10ZDJWaWFHOXZheTUwWld0MGIyNHRjR2x3Wld4cGJtVnpMbk4yWXpBZUZ3MHlNREE1TVRjd09UVTRNek5hCkZ3MHlNVEE1TVRjd09UVTRNekphTUU0eEZEQVNCZ05WQkFvVEMydHVZWFJwZG1VdVpHVjJNVFl3TkFZRFZRUUQKRXkxMFpXdDBiMjR0Y0dsd1pXeHBibVZ6TFhkbFltaHZiMnN1ZEdWcmRHOXVMWEJwY0dWc2FXNWxjeTV6ZG1NdwpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFESmVuNXZMVk9GUm8yOTdibTVzKzdoCmJta2FJOElaU05LanRrMlo1ZWxwTmhQZ05vREpQUTZsQzRDSEJIOXUrRW5kOTZIeXdQUThCUWVyS25HOTNIZFMKRk83c1Y0MkErY1V4OUJ5dDhIcGpKenF0Zjh2c1VnK1VMejhiNkdOTGNBb3RIL2pPL3lNaTNMWlJLR2hHdjNiSQo0OGlwNEJSM295QUd1RTh1dTVlcmw2OXFEQlhTTEVaOGN1T1dyVnI1V1RrM0t3L21ReUZ6T2w5RkgxM3R3by9lCkFIOUgwWkFxdCtaeHF1RkMweVNDcVgyTVNKOUpiVnVXOHdHYmZFY2R6aFhUZWlMYTRPbFR0MGhIcnkwMTFFcFQKYkJXaFFlZnh4Sm93QUhqVnI3b2lqMzh4OEhmU2tvVGk3a3Y2L0hDV05UMnJFNXREdVM1Mk1xWmkwREtXNzJxYgpBZ01CQUFHamdnRUNNSUgvTUE0R0ExVWREd0VCL3dRRUF3SUNoREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNECkFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96Q0J2QVlEVlIwUkJJRzBNSUd4Z2hoMFpXdDAKYjI0dGNHbHdaV3hwYm1WekxYZGxZbWh2YjJ1Q0tYUmxhM1J2Ymkxd2FYQmxiR2x1WlhNdGQyVmlhRzl2YXk1MApaV3QwYjI0dGNHbHdaV3hwYm1WemdpMTBaV3QwYjI0dGNHbHdaV3hwYm1WekxYZGxZbWh2YjJzdWRHVnJkRzl1CkxYQnBjR1ZzYVc1bGN5NXpkbU9DTzNSbGEzUnZiaTF3YVhCbGJHbHVaWE10ZDJWaWFHOXZheTUwWld0MGIyNHQKY0dsd1pXeHBibVZ6TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDZQpkdU9GWmZ2TTZQdk5Nd0lKUmY1U3Vzd210aDdVNHdReUFSR0pKNzhjRDdTbEV6ZFd6QjRvZjZZby8yWnRFcU1xCnNQd0R2TVkzbHlad05YcXpkNEVmYnZhMXRKN1hqTWRMb3hxNlIzZm5XbjQxUnV0aDh1NkpId003SUFoRTdzY3YKcnJyVXFsNjhiWWt2RmNuTkNyc2dlTnRmTWcrNzRwc3NRUjkwbE1iTjd1bXVETTNHdHhOZHBRdGV4ckZDV0d2MApBczI2SlcydndPT1FKNXNNem5SRjdCaDdIUkZEZDNSSkNiK1dQSGQ3NGh1QkU0eGVvUGNQZkxlYnVCNkJpSWVMCjJPaDRjaGwzUFVQUENZNHAwQmpqckNlVkhQMDUwbkdnaHFXdk02a0NZaEV0TDRqVDlYRFRhRmQ0eEJDaEg5VlUKTlM3NG1IKzViVXQ2TkRISUNielkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
          path: /resource-conversion
          port: 443
      conversionReviewVersions:
      - v1beta1
  group: tekton.dev
  names:
    categories:
    - tekton
    - tekton-pipelines
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - tekton
    - tekton-pipelines
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
  conditions:
  - lastTransitionTime: "2020-09-17T09:57:44Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-09-17T09:57:44Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
```

**Comment by adietish** [comment]
@lstocchi I see that your spec has both versions, alhpa1 and beta1:
>   versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}

My code should thus pick beta1 (the one with the higher priority). Why are things still breaking, what am I missing?

**Comment by adietish** [comment]
turns out that even though we're picking the version with the highest priority, it's still alpha1 that's requested. This is caused by a "flaw" in kubernetes-client where it would use `CustomResourceDefinitionSpec.getVersion()` instead of the version with the highest priority within the list of available versions.

[CustomResourceDefinitionContext](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java#L53)
```
  public static CustomResourceDefinitionContext fromCrd(CustomResourceDefinition crd) {
    return new CustomResourceDefinitionContext.Builder()
      .withGroup(crd.getSpec().getGroup())
      .withVersion(crd.getSpec().getVersion()) <------
      .withScope(crd.getSpec().getScope())
      .withName(crd.getMetadata().getName())
      .withPlural(crd.getSpec().getNames().getPlural())
      .withKind(crd.getSpec().getNames().getKind())
      .build();
  }
```

**Comment by adietish** [comment]
I added the change to kubernetes-client as discussed [here:](https://github.com/fabric8io/kubernetes-client/pull/2601#issuecomment-729042214): https://github.com/fabric8io/kubernetes-client/pull/2601

**Comment by adietish** [comment]
@lstocchi I updated my PR so that it now should display tekton resources in v1beta1 now. Dare to test it, please?

**Review by lstocchi — APPROVED** [review]
Awesome!!! It works perfectly now. GJ!!

**Pull request merged**
