### PR TITLE
chore: set Jenkins to use jdk11 (#257)

### LINKED ISSUE #257: Jenkinsfile is broken
Builds are now failing since 0635d86103bb0962f7520fe6bd3284368ebf589f

### PR DESCRIPTION
**Pull request by adietish**
fixes #257

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Seems I have formatting issues while reading the change on GH

**Comment by adietish** [comment]
> Seems I have formatting issues while reading the change on GH

? What's the prob exactly? I dont see formatting changes in the "Files changed" tab?

**Comment by jeffmaury** [comment]
See:

image

**Comment by adietish** [comment]
> See:
> 
> image

Here's what I see:
image

**Comment by adietish** [comment]
@jeffmaury were spaces instead of tabs in all the other places. Weird that it's not visible in GH for me.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
