### PR TITLE
pull & replace to editor fileType (#342)

### LINKED ISSUE #342: Pulling is replacing json by yaml
**Steps:**
1. ASSERT: have a JSON file with a resource
2. ASSERT: make sure it exists on cluster
3. EXEC: change it on cluster
4. EXEC: click "Pull" in the upcoming pull notification

**Result:**
The editor is replaced with the resource in YAML. The editor will thus not validate

### PR DESCRIPTION
**Pull request by adietish**
fixes #342

### CODE REVIEW

**Comment by adietish** [comment]
@lstocchi, @jeffmaury: this PR fails in the MacOS build only. 
```
com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorTest > #update should hide all notifications when resource is outdated FAILED
    java.lang.NoClassDefFoundError at ResourceEditorTest.kt:2078
```
I can't replicate this locally and this doesn't seem to happen in other PRs. I'm kinda clueless how to fix this. Any idea?

**Comment by adietish** [comment]
Note: IDEA relies on the file type for all it's parsing, content-assist etc. If you open up a yaml file and paste json into it, all the IDEA facilities wont work. My fix therefore also relies on the file type. It will not look at the actual content but relies on the file type instead. It is therefore not possible to open a yaml file, paste json into it and expect that pulling then offers you json. It will pull yaml since the file type indicates that you're editing yaml.

**Comment by adietish** [comment]
the very same error happend july 2021 in intellij-tekton: https://lists.jboss.org/archives/list/jbosstools-builds@lists.jboss.org/thread/5KBRRACRI2LXQX6M3UY3J4WFDRLKOZ6O/
```
[2021-07-02T16:59:00.094Z] [gradle-intellij-plugin :intellij-tekton-build] Cannot create
plugin from file
(/home/hudson/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2019.3/b1eea31ab3488d7613459463940cfc96244a904a/ideaIU-2019.3/plugins/java-ide-customization):
Invalid plugin descriptor 'plugin.xml': failed to resolve <xi:include>. Not
found document '/META-INF/EnforcedPlainText.xml' referenced in <xi:include
href="/META-INF/EnforcedPlainText.xml",
xpointer="xpointer(/idea-plugin/*)"/>. <xi:fallback> element is not
provided. (at plugin.xml)
```

**Comment by adietish** [comment]
Turned out that creating a mock for `PsiFile` caused the exception at runtime:
```
    private val psiFile: PsiFile = mock()
```
I still dont know why but chaning it to the following fixes the problem:
```
    private val psiFile: PsiFile = spy(PsiUtilCore.NULL_PSI_FILE)
```

**Review by lstocchi — APPROVED** [review]
LGTM

**Pull request merged**
