### PR TITLE
added verification for IJ-2022.1 (#389)

### LINKED ISSUE #389: Add IJ 2022.1 verification

### PR DESCRIPTION
**Pull request by adietish**
fixes #389

### CODE REVIEW

**Comment by adietish** [comment]
just adding `IC-2022.1` leads to the build erroring with an incompatible kotlin runtime 1.4.0 while 1.6.0 is used in the IC:
```
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
```

**Comment by adietish** [comment]
I also had to change `compileClasspath += sourceSets.main.output + configurations.testRuntime` to `compileClasspath += sourceSets.main.output + configurations.runtimeClasspath` for this to compile.
IT source set now looks as follows:
```groovy
sourceSets {
    integrationTest {
        java.srcDir file('src/it/java')
        resources.srcDir file('src/it/resources')
        compileClasspath += sourceSets.main.output + configurations.runtimeClasspath
        runtimeClasspath += output + compileClasspath
    }
}
```

**Review by jeffmaury — CHANGES_REQUESTED** [review]
L43 of IJ.yml needs to be updated as well

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
