### PR TITLE
use ActionPlaces.TOOLWINDOW_POPUP for resource tree popup menu (#705)

### LINKED ISSUE #705: "Please do not use ActionPlaces.UNKNOWN or the empty place." warning after right click on namespace
Steps to reproduce:
1. gradlew runIde
2. create new epmty project and open "Kubernetes" tab
3. expand Namespaces -> right click on some namespace -> see terminal output

logs:
```
WARN - #c.i.o.a.i.ActionPopupMenuImpl - Please do not use ActionPlaces.UNKNOWN or the empty place. Any string unique enough to deduce the popup menu location will do.
java.lang.Throwable: popup menu creation trace
        at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl.<init>(ActionPopupMenuImpl.java:58)
        at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionPopupMenu(ActionManagerImpl.java:426)
        at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.createActionPopupMenu(BackendActionManager.kt:31)
        at com.intellij.ui.PopupHandler$2.invokePopup(PopupHandler.java:136)
        at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:47)
        at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
        at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:394)
        at java.desktop/java.awt.Component.processEvent(Component.java:6419)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### PR DESCRIPTION
**Pull request by adietish**
fixes #705

### CODE REVIEW

**Comment by adietish** [comment]
@olkornii please review

**Comment by olkornii** [comment]
@adietish Hi, I've tried issue-705 branch. There is no Popup warning anymore. But I've noticed another warnings.
Steps:
1. open Kubernetes tab
2. expand "Namespaces"
3. right click on some namespace
4. select "Use namespace"
5. warning appears:
`024-01-15 11:46:57,886 [  69368]   WARN - i.f.k.c.r.Readiness - Namespace is not a Readiable resource. It needs to be one of [Node, Deployment, ReplicaSet, StatefulSet, Pod, ReplicationController]`

**Review by olkornii — APPROVED** [review]
Warning is gone. See last comment.

**Comment by adietish** [comment]
@olkornii: the warning that you noticed is not related. It is caused by the kubernetes client: https://github.com/fabric8io/kubernetes-client/issues/2672. It points us to bump the kubernetes-client at some point.

**Pull request merged**
