### PR TITLE
support multiple resources in the editor (#549)

### LINKED ISSUE #549: Feature Request: Support Multi Resource Files
I use yaml files, which contain more than one resource kind. All marked as invalid.
It seems there have to be only the same kind of resource per one file.
Feature Request: support Multi Resource Files

Example
```
apiVersion: v1
kind: Secret
metadata:
  name: jhipster-grafana-credentials
  namespace: default
data:
  username: xxxxxxx
  password: xxxxxxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhipster-grafana
```

Error Message:
`Invalid kubernetes yaml/json`

### PR DESCRIPTION
**Pull request by adietish**
fixes #549

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: can you please test this? I'll now start fixig/adding unit tests.

**Comment by cloorc** [comment]
@adietish Hi man. It seems like there are several tests doesn't pass in `com.redhat.devtools.intellij.kubernetes.model.resource.NonCachingSingleResourceOperatorTest`. Please have a look:

image

**Comment by adietish** [comment]
@sbouchet, @robstryker. @jeffmaury: to test this you can either use the doc from the issue:
```
apiVersion: v1
kind: Secret
metadata:
  name: jhipster-grafana-credentials
  namespace: default
data:
  username: xxxxxxx
  password: xxxxxxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhipster-grafana
```
or a more complex one:
```
kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
  labels:
    smurf: grumpy
spec:
  selector:
    app: apple 
  ports:
    - port: 5678 # Default port for image
---
kind: Pod
apiVersion: v1
metadata:
  name: banana-app
  labels:
    app: banana
spec:
  containers:
    - name: banana-app
      image: hashicorp/http-echo
      args:
        - "-text=banana"
---
kind: Service
apiVersion: v1
metadata:
  name: banana-service
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: Exact
            path: /apple
            backend:
              service:
                name: apple-service
                port:
                  number: 5678
          - pathType: Exact
            path: /banana
            backend:
              service:
                name: banana-service
                port:
                  number: 5678
```

**Comment by jeffmaury** [comment]
Tried but once all resources have been created, I modified one and was asked for Push and got an error as a result.

kube

**Comment by adietish** [comment]
> Tried but once all resources have been created, I modified one and was asked for Push and got an error as a result.

Replicated this. This actually is not related to the multi-resource support. This also happens when you edit a single pod. 
Furthermore this seems related to the `spec` in the pod, the error complains about prohibited changes in `spec`. Adding a label in one of the `Service`s works fine.
Interestingly `kubectl apply` works here. Digging into this I found longs threads in the kubernetes-client where differences in their `#createOrReplace` method and `kubectls apply`. 
I'll takle this in a separate issue.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by sbouchet — APPROVED** [review]
Played around to create/modify/delete resources on minikube. LGTM

**Pull request merged**
