### PR TITLE
fixed ResourceEditor#title for invalid document (#314)

### LINKED ISSUE #314: Editor: editor with cluster resource should display resourcename@namespace even if invalid
depends on #308 which has to be merged first (because it fixes portions that this depends on)

**Steps:**
1. EXEC: edit resource from cluster
2. ASSERT: editor title shows **[resourcename]@[namespace]**
3. EXEC: insert **aaaaa** in front of the file so that it gets invalid
```
aaa---
apiVersion: "apps/v1"
```
4. ASSERT: editor title still shows **[resourcename]@[namespace]**
5. EXEC: close window or restart IJ
6. ASSERT: editor is reopened after restart (or reopening the same project)
7. EXEC: look at the editor title

**Result:**
editor title shows **[resourcename].yml**

**Expected result:**
editor title should still show **[resourcename]@[namespace]**

### PR DESCRIPTION
**Pull request by adietish**
fixes #314

### CODE REVIEW

**Comment by adietish** [comment]
@olkornii can you please check what's wrong with the ITs here? I looked into the code and don't see where they're failing. I can't run the ITs on my mac. Should maybe make them run on Mac at some point so that I can help.

**Comment by adietish** [comment]
@olkornii found the following issue:
**Steps:**
1. ASSERT: have CRC running
2. EXEC: double click (or use "Edit..." in the ctx menu) **[cluster] > Nodes > [node]**

**Result:**
Editor shows up but has no toolbar. Editor title is **[node-name].yml**

**Expected Result:**
Editor should have toolbar and title should be **[nodename]@[namespace]**

**Comment by lstocchi** [comment]
> @olkornii found the following issue: **Steps:**
> 
> 1. ASSERT: have CRC running
> 2. EXEC: double click (or use "Edit..." in the ctx menu) **[cluster] > Nodes > [node]**
> 
> **Result:** Editor shows up but has no toolbar. Editor title is **[node-name].yml** image
> 
> **Expected Result:** Editor should have toolbar and title should be **[nodename]@[namespace]**

A node is a non-namespace resource so it would be wrong to show nodename@namespace. Nodes contains namespaces not the opposite. I think the current behavior is correct

**Review by lstocchi — CHANGES_REQUESTED** [review]
I tried following your example to replicate the issue. The fix works but when i start typing `aaa` before `---` i get this error

```
kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
	at com.redhat.devtools.intellij.kubernetes.tree.OpenShiftStructure.isParentDescriptor(OpenShiftStructure.kt:162)
	at com.redhat.devtools.intellij.kubernetes.tree.TreeStructure.isParentDescriptor(TreeStructure.kt:94)
	at com.redhat.devtools.intellij.kubernetes.tree.TreeUpdater.getPotentialParentNodes(TreeUpdater.kt:117)
	at com.redhat.devtools.intellij.kubernetes.tree.TreeUpdater.access$getPotentialParentNodes(TreeUpdater.kt:34)
	at com.redhat.devtools.intellij.kubernetes.tree.TreeUpdater$added$1.run(TreeUpdater.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:191)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:158)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:473)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by adietish** [comment]
> P.S: i did the test with a pod on crc. Maybe by merging #326 and rebasing this one it would be solved??

yes exactly, this should be gone once #326 is merged

**Comment by adietish** [comment]
@lstocchi: rebased to #326. Please re-review

**Review by lstocchi — APPROVED** [review]
LGTM

**Pull request merged**
