### PR TITLE
added a link & balloon for error details (#537)

### LINKED ISSUE #537: logs/terminal: allow to inspect error details
**Steps:**
1. EXEC: create a deployment via the following:
```
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "nginx"
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - image: "nginx"
        name: "nginx"
        ports:
        - containerPort: 80
          protocol: "TCP"
      initContainers:
      - image: "alpine"
        name: "init1"
```
2. EXEC: select the deployment and pick "Terminal" in the context menu
3. EXEC: select the container "init"
4. ASSERT: an error is displayed in the terminal pane. 
image
5. EXEC: try to figure out what exactly went wrong

**Result:**
You just get the generic message that the terminal could not connect to the container. There are no details about why this happened.

**Expected result:**
You should be able to inspect the details of the connection error

### PR DESCRIPTION
**Pull request by adietish**
fixes #537

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: The error now has a link "Details" that would display the error details if clicked:
image
Please review.

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: with this PR there's now a "Details" link in the error that when clicked, shows the cause:
image

ps. There's an unwanted space btw. "Details" and "Reconnect". I failed to eliminate it. The link widget that I used for the error text with the links requests an additional space behind "Details".

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: with this PR the error pane in the terminal would offer a link for the error details:
image
Please review.

ps. there's unwanted space btw. "Details" and "Reconnect". Tried to eliminate it but it looks as if the preferred size of the `HyperlinkLabel` would include empty space after the text that I failed to remove.

**Comment by adietish** [comment]
@jeffmaury I added fixed space to the right (tried measuring insets, scrollbars etc. but nothing worked). Please try again.

**Review by jeffmaury — APPROVED** [review]
LGTM although I have extra space on the right:

image

**Pull request merged**
