### PR TITLE
added diff action (#224)

### LINKED ISSUE #224: As a user I would like to see a diff of my editor with the remote resource
depends on #218 

When the resource on the cluster changed the editor notifies the user about this change: it'll either automatically reload the editor if there are no local changes or it'll offer the user to reload the resource in the local editor. In this case it would be handy to see what exactly changed. `HttpFileEditor` (a subclass for `RemoteFileEditor`) offers a diff in its toolbar. It would be nice to have something similar:
image

### PR DESCRIPTION
**Pull request by adietish**
fixes #224

### CODE REVIEW

**Comment by adietish** [comment]
Diff action is available in toolbar too: 
image
 It opens up the default diff/merge facility that's build into IJ, nice stuff:
image

**Comment by adietish** [comment]
found bugs, fixing before re-requesting review.

**Comment by adietish** [comment]
@lstocchi, @jeffmaury: in the notification there's a "Diff" link. This opens a diff dialog. If you don't change anything, the editor stays unchanged. If you change the editor document in the diff window, the editor gets updated as if it had pulled the latest version.

**Review by lstocchi — COMMENTED** [review]
While testing it this error came out. 
I just have a yaml file opened in my editor (it was already opened, so IJ started with this up), i click on diff, the window opens up correctly and everything works fine but this error is printed. This happens everytime i click on `diff`

```
Details: Current thread: Thread[Showing diff...,4,Idea Thread Group] 349831817
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 2049961228

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:918)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.getCachedPsiFile(FileManagerImpl.java:360)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:140)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:121)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getPsiFile(PsiDocumentManagerBase.java:84)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.getPsiFile(PsiDocumentManagerImpl.java:67)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.getFileType(ResourceEditor.kt:298)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.diff(ResourceEditor.kt:356)
	at com.redhat.devtools.intellij.kubernetes.editor.actions.DiffAction$actionPerformed$1.run(DiffAction.kt:35)
	at com.redhat.devtools.intellij.kubernetes.actions.ExtensionsKt$run$1.run(Extensions.kt:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by adietish** [comment]
> While testing it this error came out. I just have a yaml file opened in my editor (it was already opened, so IJ started with this up), i click on diff, the window opens up correctly and everything works fine but this error is printed. This happens everytime i click on `diff`

@lstocchi Thanks for reporting! Fixed it. I also fixed another bug where the "Diff" link would also be available for resources that dont exist on the cluster (no diff possible).
Please re-test.

**Review by lstocchi — CHANGES_REQUESTED** [review]
It seems the diff caches the editor content somehow and if there is an error it still sees it even when this is fixed.
I have a file with this (a wrong written resource as it misses the metadata fields)

```
apiVersion: v1
data:
  username: YWRtaW4=222
  password: MWYyZDFlMmU2N2Rm
kind: Secret
type: Opaque
```

if i click on diff it correctly print the error `Error showing diff: Could not show diff editor vs resource from cluster: initialResource.metadata must not be null`.

I then fix the resource by adding the metadata fields
```
apiVersion: v1
data:
  username: YWRtaW4=222
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: mysecret2
  namespace: default
type: Opaque
```

but if i click on diff again, the error is shown as if the resource was not edited

I guess this is connected to https://github.com/redhat-developer/intellij-kubernetes/issues/377 ??

**Comment by adietish** [comment]
> if i click on diff it correctly print the error `Error showing diff: Could not show diff editor vs resource from cluster: initialResource.metadata must not be null`.

I'd prefer this not to be possible at all. This is no proper error really, it's more of "this is not possible, resource does not exist on the cluster". I'll look into this and see how I can improve it.

> I guess this is connected to #377 ??

very likely that this is the same bug. Looking into it.

**Comment by lstocchi** [comment]
> I assume that you clicked on the icon in the toolbar, correct? I'd prefer this not to error but to inform that a diff is not possible, since this is not a proper error. I'd also prefer this to inform via the editor notification rather than ide notification: image

My concern wasn't about this but the error i faced later on. The error message here is clear so good for me. Either it is shown in editor notification or ide notification it's up to you. I don't have a strong opinion on it. It's the same.

> Thanks for filing this one, it's a separate issue as you already noticed.

Welcome :)

**Comment by adietish** [comment]
@lstocchi: fix for the "caching" of the resource was merged (#379), fix for IllegalArgumentException is pending review (#381) 
Please re-review

**Comment by adietish** [comment]
> My concern wasn't about this but the error i faced later on. The error message here is clear so good for me. Either it is shown in editor notification or ide notification it's up to you. I don't have a strong opinion on it. It's the same.
> 
I care about consistency of the error reporting. In my understanding editor related errors should be reported as error notifications within the editor. I'll file a separate issue about this.
The other 2 issues that you reported have been fixed (especially the annoying #345 where you cannot correct the yaml, the editor keeps complaining about the same error).

**Comment by lstocchi** [comment]
> I care about consistency of the error reporting. In my understanding editor related errors should be reported as error notifications within the editor. I'll file a separate issue about this. The other 2 issues that you reported have been fixed (especially the annoying #345 where you cannot correct the yaml, the editor keeps complaining about the same error).

Waiting your rebase with https://github.com/redhat-developer/intellij-kubernetes/pull/381 then i'll retest it :+1:

**Comment by adietish** [comment]
@lstocchi: all rebased, please re-review

**Review by lstocchi — APPROVED** [review]
It looks good to me.
At some point I faced a fatal error but i wasn't able to replicate it. It looks to me that the tmp file generated by the diff caused it but i don't know what i did to make this error arise. I tried again but it didn't happen :man_shrugging: . BTW if i face this again i'll open a new issue. For the rest it behaves fine. GJ :+1: 
Pasting the stacktrace so you can give it a look
```
[1597249]  ERROR - impl.file.impl.FileManagerImpl - Plugin to blame: Kubernetes by Red Hat version: 0.4.3-SNAPSHOT 
[1599017]  ERROR - impl.file.impl.FileManagerImpl - Invalid file: file:///tmp/pi_.yml 
java.lang.Throwable: Invalid file: file:///tmp/pi_.yml
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:348)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:153)
	at com.redhat.devtools.intellij.kubernetes.editor.util.ResourceEditorUtilsKt$getKubernetesResourceInfo$1.compute(ResourceEditorUtils.kt:75)
	at com.redhat.devtools.intellij.kubernetes.editor.util.ResourceEditorUtilsKt$getKubernetesResourceInfo$1.compute(ResourceEditorUtils.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:821)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.redhat.devtools.intellij.kubernetes.editor.util.ResourceEditorUtilsKt.getKubernetesResourceInfo(ResourceEditorUtils.kt:74)
	at com.redhat.devtools.intellij.kubernetes.editor.util.ResourceEditorUtilsKt.hasKubernetesResource(ResourceEditorUtils.kt:46)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory$6.invoke(ResourceEditorFactory.kt:49)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory$6.invoke(ResourceEditorFactory.kt:32)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory.create(ResourceEditorFactory.kt:127)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory.getExistingOrCreate(ResourceEditorFactory.kt:122)
	at com.redhat.devtools.intellij.kubernetes.editor.EditorFocusListener.selectionLost(EditorFocusListener.kt:56)
	at com.redhat.devtools.intellij.kubernetes.editor.EditorFocusListener.selectionChanged(EditorFocusListener.kt:25)
	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:513)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:142)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:438)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:388)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:241)
	at com.sun.proxy.$Proxy93.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$fireSelectionChanged$21(FileEditorManagerImpl.java:1576)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$6$1.run(FileEditorManagerImpl.java:1019)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:168)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2413)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:177)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:129)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:159)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:165)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$null$2(FocusManagerImpl.java:173)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Pull request merged**
