### PR TITLE
bumped schema to v1.25.3 (#501)

### LINKED ISSUE #501: bump shema to 1.25.3
we're currently using `v.1.24.2` schema. `1.25.3` went available in the meantime: https://raw.githubusercontent.com/kubernetes/kubernetes/v1.25.3/api/openapi-spec/swagger.json

### PR DESCRIPTION
**Pull request by adietish**
fixes #501

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by adietish** [comment]
@lstocchi, @jeffmaury: it's striking how much is removed with this bump:
image

The explanation is that many deprecated items were removed. The details can be read in the deprecation guide at kubernetes.io: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
> The v1.25 release will stop serving the following deprecated API versions:
* CronJob
* EndpointSlice
* Event
* HorizontalPodAutoscaler
* PodDisruptionBudget
* PodSecurityPolicy
* PodSecurityPolicy
* RuntimeClass

One could wonder if we should support multiple schema.
Thoughts?

**Comment by jeffmaury** [comment]
> @lstocchi, @jeffmaury: it's striking how much is removed with this bump: image
> 
> The explanation is that many deprecated items were removed. The details can be read in the deprecation guide at kubernetes.io: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
> 
> > The v1.25 release will stop serving the following deprecated API versions:
> > 
> > * CronJob
> > * EndpointSlice
> > * Event
> > * HorizontalPodAutoscaler
> > * PodDisruptionBudget
> > * PodSecurityPolicy
> > * PodSecurityPolicy
> > * RuntimeClass
> 
> One could wonder if we should support multiple schema. Thoughts?

We should support several Kubernetes versions and not only the last one.
In IntelliJ Tekton they removed some CRDs but I kept the schemas

**Comment by mohitsuman** [comment]
@adietish What's the status of this PR ? Should we merge this to main ?

**Review by jeffmaury — COMMENTED** [review]
Is it still valid ?

**Comment by adietish** [comment]
The issue is, the PR isnt. The PR is badly incomplete. It is simply bumping the supported schema where support for multiple schema should be provided (not just the latest but query the cluster for supported ones and then provide a matching schema in the editor).
I'm closing this PR since it's outdated.

**Pull request closed without merging**
