### PR TITLE
chore: migrate build to 2024.2

### LINKED ISSUE #780: Support building against 2024.2
related to https://github.com/redhat-developer/intellij-openshift-connector/issues/889

Current Next EAP nightly ( 2024.2 ) is failing due to major changes.
With RC out, time to get this fixed.

### PR DESCRIPTION
**Pull request by sbouchet**
fixes #780

### CODE REVIEW

**Comment by adietish** [comment]
@sbouchet: i tried to find a solution for the kotlin incompatibility reported for IC-2022.3. It looks to me as if bumping `sinceVersion` to `2023.1` would solve this. Bumping would be a no-brainer since 23.1 is 1.5y behind current.

**Comment by adietish** [comment]
Here's another suggestion: Could we add @AlexanderBartash as co-author to give him credits for the important help he gave?

**Comment by adietish** [comment]
@sbouchet:

> Here's another suggestion: Could we add @AlexanderBartash as co-author to give him credits for the important help he gave?

Added his solution, adding @AlexanderBartov as author in the PR for the support of multi-kubeconfigs: https://github.com/redhat-developer/intellij-kubernetes/pull/781/commits/9f99cd6873a2a8914e6b8baabc7b10440c05bcd5

**Comment by AlexanderBartash** [comment]
> > Here's another suggestion: Could we add @AlexanderBartash as co-author to give him credits for the important help he gave?
> 
> Unfortunately forced push my branch and lost contribution from @AlexanderBartash :(

Do not mind it.

**Review by adietish — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
